{% set name = "pybind11-numpy-example" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybind11_numpy_example-{{ version }}.tar.gz
  sha256: a7b5d9a6e34d014a35d8479eaf8a82f246dec7cc4e82dc8374c59f8fd805ed79

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - ninja
  host:
    - numpy
    - pip
    - pybind11
    - python
    - scikit-build-core
  run:
    - python

test:
  imports:
    - pybind11_numpy_example
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pytest -v

about:
  home: https://github.com/ssciwr/pybind11-numpy-example
  summary: An example of using numpy with pybind11
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://pybind11-numpy-example.readthedocs.io/

extra:
  recipe-maintainers:
    - lkeegan
